### ISSUE TITLE
Audio ogg are always published as video

### ISSUE THREAD

**Issue by 20** [RedeMocambos/baobaxia#137] opened 2015-04-03 03:38 UTC
Even if you choose audio it publish as video

**Comment by agger-magenta** [comment] 2015-04-07 16:42
I can look at that! Anyone working on it now?

**Comment by agger-magenta** [comment] 2015-04-12 17:21
I can't reproduce this! 

This audio file (.ogg) was published as an audio file without any problem: http://baobaxia.modspil.dk/#mocambos/hyndla/media/3cbae6b5-eed0-46f9-a356-6c457044283e

Was this already fixed?

**Comment by 20** [comment] 2015-04-12 17:24
Alo!

Il 12/04/2015 14:21, Carsten Agger ha scritto:
> This audio file (.ogg) was published as an audio file without any
> problem:
> http://baobaxia.modspil.dk/#mocambos/hyndla/media/3cbae6b5-eed0-46f9-a356-6c457044283e
> 
> Was this already fixed?

No, I think..

Abraço,
Vince

-- 
NPDD - Núcleo de Pesquisa e Desenvolvimento Digital
Casa de Cultura Tainã / Rede Mocambos / Mercado Sul / Altakamul

**Comment by agger-magenta** [comment] 2015-04-12 18:35
Do you know how to reproduce? All I did was upload a plain .OGG audio file
and it arrived OK as audio.

2015-04-12 19:24 GMT+02:00 Vince <notifications@github.com>:

> Alo!
>
> Il 12/04/2015 14:21, Carsten Agger ha scritto:
> > This audio file (.ogg) was published as an audio file without any
> > problem:
> >
> http://baobaxia.modspil.dk/#mocambos/hyndla/media/3cbae6b5-eed0-46f9-a356-6c457044283e
> >
> > Was this already fixed?
>
> No, I think..
>
> Abraço,
> Vince
>
> --
> NPDD - Núcleo de Pesquisa e Desenvolvimento Digital
> Casa de Cultura Tainã / Rede Mocambos / Mercado Sul / Altakamul
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/RedeMocambos/baobaxia/issues/137#issuecomment-92091076>
> .
>



-- 
Carsten Agger
Magenta ApS
Åbogade 15
8200 Århus N

Tlf  +45 2086 5010
http://www.magenta-aps.dk
carstena@magenta-aps.dk

**Comment by 20** [comment] 2015-04-12 18:44
Ali

Il 12/04/2015 15:35, Carsten Agger ha scritto:
> Do you know how to reproduce? All I did was upload a plain .OGG audio file
> and it arrived OK as audio.
> 

Maybe it's related only to multiupload (galeria)..

Abraço,
Vince


-- 
NPDD - Núcleo de Pesquisa e Desenvolvimento Digital
Casa de Cultura Tainã / Rede Mocambos / Mercado Sul / Altakamul

**Comment by agger-magenta** [comment] 2015-04-15 06:41
I can't reproduce this! I think it works.

I uploaded a gallery of four .OGG audio files, specifying audio, and they all uploaded perfectly as audio.

Unless there's some edge case where we see the bug, I think this ticket can be closed.

**Comment by agger-magenta** [comment] 2015-04-20 10:18
I tried a couple of more times. Audio OGGs specified as audio are always published as audio.

Closing this until it reappears.

**Closed by agger-magenta** 2015-04-20 10:18 UTC
Labels: 0 Priority, interface, release 1.0
